version: "2"
services:
  app:
    build: .
    command: ./start-dev.sh
    ports:
      - "8080:8080"
    volumes:
      - $PWD:/app
    working_dir: /app
    links:
      - neo4j
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
